'use strict';
/* Restaurant compatibility gate: the extracted Core must reproduce the outputs that the
   source repository produced at 388e48a (golden generated by scripts/generate-source-golden.cjs). */
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const core=require('../src/rubik-seo-geo-core.js');
const pub=require('../src/rubik-seo-geo-publisher.js');

const FIXTURES=path.join(__dirname,'fixtures');
const golden=JSON.parse(fs.readFileSync(path.join(FIXTURES,'golden','source-388e48a-publish.json'),'utf8'));
const scrub=x=>JSON.parse(JSON.stringify(x).replace(/\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(\.\d+)?Z/g,'<ISO>'));

const lumina=()=>{const c=JSON.parse(fs.readFileSync(path.join(FIXTURES,'restaurant-lumina-state.json'),'utf8'));c.seo=core.reconcile(c);c.seo.site.baseUrl='https://restaurant.example.test/';c.seo.business.category='Restaurante mediterráneo';c.seo.business.cuisine=['Mediterránea'];return c;};
const realEstate=()=>{const c={brand:{name:'Casa Norte'},hero:{body:'Asesoría de compra independiente.'},business:{name:'Casa Norte',address:{city:'Alicante',country:'ES'}},services:[{id:'s1',name:'Búsqueda de vivienda',short:'Representación del comprador.'}],seo:core.defaults()};c.seo.adapterId='real-estate';c.seo.business.category='Buyer Agent';c.seo.site.baseUrl='https://casa-norte.example.test/';return c;};

test('golden was generated from the recorded source commit',()=>{
  assert.equal(golden.source,'Juanmaes83/WEB-RESTAURACI-N-PREMIUM-DIN-MICA@388e48a98e881aff4adf26f16a0679dc3e1f11f5');
});

for(const [name,factory] of Object.entries({lumina,realEstate})){
  for(const env of ['production','preview']){
    test(`Core reproduces source ${name} ${env} publish output`,()=>{
      const p=pub.publish(factory(),env);
      assert.deepEqual(scrub({seo:p.seo,publisher:p.publisher,preview:core.preview(factory())}),golden.cases[`${name}:${env}`]);
    });
  }
}
